---
title: "Clustering IDI"
author: "Mochammad Yusuf Maulana"
date: "12/18/2021"
output: html_document
---

# LOAD LIBRARY

```{r message=FALSE, warning=FALSE}
library(knitr)
library(REdaS)
library(clValid)
library(purrr)
library(factoextra)
```

# READ DATA

```{r}
IDI2020 = read.csv("IDI 2020.csv", header = T)
rownames(IDI2020) = IDI2020[,1]
IDI2020 = IDI2020[,-1]

kable(head(IDI2020))
summary(IDI2020) #deskripsi statistik
#data memiliki satuan yang sama, tidak perlu dilakukan standardisasi
```

# *Data Preprocessing*
## Mengatasi Outlier
```{r}
boxplot(IDI2020) 
#terdapat outlier

# winsorizing
for(i in c(2)){
  qnt <- quantile(IDI2020[,i], probs=c(.25, .75), na.rm = T)
  caps <- quantile(IDI2020[,i], probs=c(.05, .95), na.rm = T)
  H <- 1.5 * IQR(IDI2020[,i], na.rm = T)
  IDI2020[,i][IDI2020[,i] < (qnt[1] - H)] <- caps[1]
  IDI2020[,i][IDI2020[,i] > (qnt[2] + H)] <- caps[2]
}

boxplot(IDI2020) 
#data bebas outlier
```

## Cek Asumsi Multikolinearitas

```{r}
bart_spher(IDI2020)
# gagal tolak Ho. Artinya tidak ada gejala multikolinearitas
```

# Menentukan Jumlah k Optimum

```{r}
#membuat plot number of cluster vs total within sum of squares
fviz_nbclust(IDI2020, hcut, method = "wss") 
#k optimal = 6
```

```{r}
fviz_nbclust(IDI2020, hcut, method = "silhouette") 
#k optimal = 7
```

```{r}

#membuat plot number of clusters vs gap statistic 
gap_stat <- clusGap(IDI2020,
                    FUN = hcut,
                    K.max = 10, #maximum cluster
                    B = 50) #total iterasi bootstrap

fviz_gap_stat(gap_stat) 
#k optimal = 1
```

# Uji Validitas

```{r}
intern = clValid(IDI2020, 2:7,
                 clMethods = c("hierarchical"),
                 validation = "internal")
summary(intern)
#klaster terbaik = 2 pake hirarki
```

# *Agglomerative Coefficient*

```{r}
m <- c("single","complete","ward", "average")
names(m) <- c("single","complete","ward", "average") 

ac <- function(x){
  agnes(IDI2020,method=x)$ac
}

map_dbl(m,ac)
# metode ward terbaik
```

# Visualisasi Dendogram

```{r}
data.hcc = IDI2020 %>% 
  dist(method = "euclidean") %>%
  hclust(method = "ward.D2")

#library(factoextra)
fviz_dend(data.hcc, k =2,
          cex = 0.6, palette = "jco",
          rect = TRUE, rect_border = "jco",
          rect_fill = TRUE,
          main = "Cluster Dendogram (Ward's Method)")
```

# *Cluster Profiling*

```{r}
jarak=dist(IDI2020)
res4 = hclust(jarak, method = "ward.D2")
t=cutree(res4,k=2)
table(t) 
#klaster 1 ada 25, klaster 2 ada 9
```

```{r}
aggregate(IDI2020, list(t), mean)
```